from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


CRITICAL_RUNTIME_FILES = [
    "services/api/src/zuno/main.py",
    "services/api/src/zuno/api/router.py",
    "services/api/src/zuno/api/v1/__init__.py",
    "services/api/src/zuno/api/v1/workspace.py",
    "services/api/src/zuno/database/init_data.py",
    "services/api/src/zuno/database/session.py",
    "services/api/src/zuno/database/metadata.py",
    "services/api/src/zuno/database/models/__init__.py",
    "services/api/src/zuno/database/models/agent.py",
    "services/api/src/zuno/database/models/agent_skill.py",
    "services/api/src/zuno/database/models/base.py",
    "services/api/src/zuno/database/models/dialog.py",
    "services/api/src/zuno/database/models/history.py",
    "services/api/src/zuno/database/models/knowledge.py",
    "services/api/src/zuno/database/models/knowledge_file.py",
    "services/api/src/zuno/database/models/knowledge_task.py",
    "services/api/src/zuno/database/models/llm.py",
    "services/api/src/zuno/database/models/mcp_agent.py",
    "services/api/src/zuno/database/models/mcp_server.py",
    "services/api/src/zuno/database/models/mcp_user_config.py",
    "services/api/src/zuno/database/models/memory_history.py",
    "services/api/src/zuno/database/models/message.py",
    "services/api/src/zuno/database/models/role.py",
    "services/api/src/zuno/database/models/tool.py",
    "services/api/src/zuno/database/models/usage_stats.py",
    "services/api/src/zuno/database/models/user.py",
    "services/api/src/zuno/database/models/user_role.py",
    "services/api/src/zuno/database/models/workspace_session.py",
    "services/api/src/zuno/database/dao/__init__.py",
    "services/api/src/zuno/database/dao/agent.py",
    "services/api/src/zuno/database/dao/agent_skill.py",
    "services/api/src/zuno/database/dao/dialog.py",
    "services/api/src/zuno/database/dao/history.py",
    "services/api/src/zuno/database/dao/knowledge.py",
    "services/api/src/zuno/database/dao/knowledge_file.py",
    "services/api/src/zuno/database/dao/knowledge_task.py",
    "services/api/src/zuno/database/dao/llm.py",
    "services/api/src/zuno/database/dao/mcp_agent.py",
    "services/api/src/zuno/database/dao/mcp_server.py",
    "services/api/src/zuno/database/dao/mcp_stdio_server.py",
    "services/api/src/zuno/database/dao/mcp_user_config.py",
    "services/api/src/zuno/database/dao/memory_history.py",
    "services/api/src/zuno/database/dao/message.py",
    "services/api/src/zuno/database/dao/role.py",
    "services/api/src/zuno/database/dao/tool.py",
    "services/api/src/zuno/database/dao/usage_stats.py",
    "services/api/src/zuno/database/dao/user.py",
    "services/api/src/zuno/database/dao/user_role.py",
    "services/api/src/zuno/database/dao/workspace_session.py",
    "src/backend/zuno/services/__init__.py",
    "services/api/src/zuno/services/queue/runner.py",
    "services/api/src/zuno/services/queue/workers.py",
    "services/api/src/zuno/services/queue/client.py",
    "services/api/src/zuno/services/queue/messages.py",
    "services/api/src/zuno/services/pipeline/__init__.py",
    "services/api/src/zuno/services/pipeline/manager.py",
    "services/api/src/zuno/services/pipeline/models.py",
    "services/api/src/zuno/services/pipeline/stages.py",
    "services/api/src/zuno/services/storage/__init__.py",
    "services/api/src/zuno/services/rag/vector_db/__init__.py",
    "services/api/src/zuno/config/__init__.py",
    "services/api/src/zuno/config/es_index.py",
    "services/api/src/zuno/config.example.yaml",
    "services/api/src/zuno/schema/__init__.py",
    "services/api/src/zuno/schema/common.py",
    "services/api/src/zuno/schema/schemas.py",
    "services/api/src/zuno/mcp_servers/__init__.py",
    "services/api/src/zuno/mcp_servers/remote_proxy/__init__.py",
    "services/api/src/zuno/mcp_servers/remote_proxy/main.py",
    "services/api/src/zuno/core/__init__.py",
    "services/api/src/zuno/core/agents/__init__.py",
    "services/api/src/zuno/core/agents/general_agent.py",
    "services/api/src/zuno/core/graphs/domain_qa_graph.py",
    "services/api/src/zuno/core/models/__init__.py",
    "services/api/src/zuno/core/models/manager.py",
    "services/api/src/zuno/core/runtime/__init__.py",
    "services/api/src/zuno/core/runtime/agent_runtime.py",
    "services/api/src/zuno/settings.py",
    "services/api/src/zuno/config.yaml",
    "services/api/src/zuno/fixtures/knowledge_reindex/zuno_ascii_kb_001.md",
    "services/api/src/zuno/prompts/__init__.py",
    "services/api/src/zuno/prompts/rewrite.py",
    "services/api/src/zuno/tools/__init__.py",
    "services/api/src/zuno/tools/cli_tool/adapter.py",
    "services/api/src/zuno/tools/openapi_tool/adapter.py",
    "services/api/src/zuno/tools/send_email/cli.py",
    "services/api/src/zuno/utils/__init__.py",
    "services/api/src/zuno/utils/JWT.py",
    "services/api/src/zuno/utils/constants.py",
    "services/api/src/zuno/utils/date_utils.py",
    "services/api/src/zuno/utils/file_utils.py",
    "services/api/src/zuno/utils/hash.py",
    "services/api/src/zuno/utils/runtime_observability.py",
]


LEGACY_FILES_THAT_SHOULD_BE_GONE = [
    "src/backend/zuno/services/storage/__init__.py",
    "src/backend/zuno/services/storage/minio.py",
    "src/backend/zuno/services/storage/oss.py",
    "src/backend/zuno/database/__init__.py",
    "src/backend/zuno/database/init_data.py",
    "src/backend/zuno/database/session.py",
    "src/backend/zuno/database/metadata.py",
    "src/backend/zuno/database/models/__init__.py",
    "src/backend/zuno/database/models/agent.py",
    "src/backend/zuno/database/models/agent_skill.py",
    "src/backend/zuno/database/models/base.py",
    "src/backend/zuno/database/models/dialog.py",
    "src/backend/zuno/database/models/history.py",
    "src/backend/zuno/database/models/knowledge.py",
    "src/backend/zuno/database/models/knowledge_file.py",
    "src/backend/zuno/database/models/knowledge_task.py",
    "src/backend/zuno/database/models/llm.py",
    "src/backend/zuno/database/models/mcp_agent.py",
    "src/backend/zuno/database/models/mcp_server.py",
    "src/backend/zuno/database/models/mcp_user_config.py",
    "src/backend/zuno/database/models/memory_history.py",
    "src/backend/zuno/database/models/message.py",
    "src/backend/zuno/database/models/role.py",
    "src/backend/zuno/database/models/tool.py",
    "src/backend/zuno/database/models/usage_stats.py",
    "src/backend/zuno/database/models/user.py",
    "src/backend/zuno/database/models/user_role.py",
    "src/backend/zuno/database/models/workspace_session.py",
    "src/backend/zuno/database/dao/__init__.py",
    "src/backend/zuno/database/dao/agent.py",
    "src/backend/zuno/database/dao/agent_skill.py",
    "src/backend/zuno/database/dao/dialog.py",
    "src/backend/zuno/database/dao/history.py",
    "src/backend/zuno/database/dao/knowledge.py",
    "src/backend/zuno/database/dao/knowledge_file.py",
    "src/backend/zuno/database/dao/knowledge_task.py",
    "src/backend/zuno/database/dao/llm.py",
    "src/backend/zuno/database/dao/mcp_agent.py",
    "src/backend/zuno/database/dao/mcp_server.py",
    "src/backend/zuno/database/dao/mcp_stdio_server.py",
    "src/backend/zuno/database/dao/mcp_user_config.py",
    "src/backend/zuno/database/dao/memory_history.py",
    "src/backend/zuno/database/dao/message.py",
    "src/backend/zuno/database/dao/role.py",
    "src/backend/zuno/database/dao/tool.py",
    "src/backend/zuno/database/dao/usage_stats.py",
    "src/backend/zuno/database/dao/user.py",
    "src/backend/zuno/database/dao/user_role.py",
    "src/backend/zuno/database/dao/workspace_session.py",
    "src/backend/zuno/api/services/__init__.py",
    "src/backend/zuno/api/services/agent.py",
    "src/backend/zuno/api/services/agent_skill.py",
    "src/backend/zuno/api/services/capability.py",
    "src/backend/zuno/api/services/completion.py",
    "src/backend/zuno/api/services/dialog.py",
    "src/backend/zuno/api/services/history.py",
    "src/backend/zuno/api/services/knowledge.py",
    "src/backend/zuno/api/services/knowledge_file.py",
    "src/backend/zuno/api/services/llm.py",
    "src/backend/zuno/api/services/mcp_agent.py",
    "src/backend/zuno/api/services/mcp_chat.py",
    "src/backend/zuno/api/services/mcp_server.py",
    "src/backend/zuno/api/services/mcp_stdio_server.py",
    "src/backend/zuno/api/services/mcp_user_config.py",
    "src/backend/zuno/api/services/message.py",
    "src/backend/zuno/api/services/mineru.py",
    "src/backend/zuno/api/services/tool.py",
    "src/backend/zuno/api/services/upload.py",
    "src/backend/zuno/api/services/usage_stats.py",
    "src/backend/zuno/api/services/user.py",
    "src/backend/zuno/api/services/wechat.py",
    "src/backend/zuno/api/services/workspace.py",
    "src/backend/zuno/api/services/workspace_session.py",
    "src/backend/zuno/api/v1/__init__.py",
    "src/backend/zuno/api/v1/agent.py",
    "src/backend/zuno/api/v1/agent_skill.py",
    "src/backend/zuno/api/v1/capability.py",
    "src/backend/zuno/api/v1/completion.py",
    "src/backend/zuno/api/v1/config.py",
    "src/backend/zuno/api/v1/dialog.py",
    "src/backend/zuno/api/v1/history.py",
    "src/backend/zuno/api/v1/knowledge.py",
    "src/backend/zuno/api/v1/knowledge_file.py",
    "src/backend/zuno/api/v1/llm.py",
    "src/backend/zuno/api/v1/mcp_agent.py",
    "src/backend/zuno/api/v1/mcp_chat.py",
    "src/backend/zuno/api/v1/mcp_server.py",
    "src/backend/zuno/api/v1/mcp_stdio_server.py",
    "src/backend/zuno/api/v1/mcp_user_config.py",
    "src/backend/zuno/api/v1/message.py",
    "src/backend/zuno/api/v1/tool.py",
    "src/backend/zuno/api/v1/upload.py",
    "src/backend/zuno/api/v1/usage_stats.py",
    "src/backend/zuno/api/v1/user.py",
    "src/backend/zuno/api/v1/wechat.py",
    "src/backend/zuno/api/v1/workspace.py",
    "src/backend/zuno/api/__init__.py",
    "src/backend/zuno/api/JWT.py",
    "src/backend/zuno/api/router.py",
    "src/backend/zuno/api/errcode/__init__.py",
    "src/backend/zuno/api/errcode/base.py",
    "src/backend/zuno/api/errcode/user.py",
    "src/backend/zuno/services/pipeline/__init__.py",
    "src/backend/zuno/services/pipeline/manager.py",
    "src/backend/zuno/services/pipeline/models.py",
    "src/backend/zuno/services/pipeline/stages.py",
    "src/backend/zuno/services/queue/__init__.py",
    "src/backend/zuno/services/queue/client.py",
    "src/backend/zuno/services/queue/messages.py",
    "src/backend/zuno/services/queue/runner.py",
    "src/backend/zuno/services/queue/workers.py",
    "src/backend/zuno/services/retrieval/__init__.py",
    "src/backend/zuno/services/retrieval/fusion.py",
    "src/backend/zuno/services/retrieval/models.py",
    "src/backend/zuno/services/retrieval/orchestrator.py",
    "src/backend/zuno/services/retrieval/planner.py",
    "src/backend/zuno/services/retrieval/retrievers.py",
    "src/backend/zuno/services/rewrite/__init__.py",
    "src/backend/zuno/services/rewrite/markdown_rewrite.py",
    "src/backend/zuno/services/rewrite/query_write.py",
    "src/backend/zuno/middleware/__init__.py",
    "src/backend/zuno/middleware/trace_id_middleware.py",
    "src/backend/zuno/middleware/white_list_middleware.py",
    "src/backend/zuno/config/__init__.py",
    "src/backend/zuno/config/es_index.py",
    "src/backend/zuno/config/tool.json",
    "src/backend/zuno/config/avatars.json",
    "src/backend/zuno/config/mcp_server.json",
    "src/backend/zuno/config.example.yaml",
    "src/backend/zuno/schema/__init__.py",
    "src/backend/zuno/schema/agent.py",
    "src/backend/zuno/schema/agent_skill.py",
    "src/backend/zuno/schema/capability.py",
    "src/backend/zuno/schema/chunk.py",
    "src/backend/zuno/schema/common.py",
    "src/backend/zuno/schema/completion.py",
    "src/backend/zuno/schema/dialog.py",
    "src/backend/zuno/schema/knowledge.py",
    "src/backend/zuno/schema/llm.py",
    "src/backend/zuno/schema/mcp.py",
    "src/backend/zuno/schema/mcp_user_config.py",
    "src/backend/zuno/schema/rerank.py",
    "src/backend/zuno/schema/schemas.py",
    "src/backend/zuno/schema/search.py",
    "src/backend/zuno/schema/tool.py",
    "src/backend/zuno/schema/usage_stats.py",
    "src/backend/zuno/schema/workspace.py",
    "src/backend/zuno/mcp_servers/__init__.py",
    "src/backend/zuno/mcp_servers/remote_proxy/__init__.py",
    "src/backend/zuno/mcp_servers/remote_proxy/main.py",
    "src/backend/zuno/core/__init__.py",
    "src/backend/zuno/core/agents/__init__.py",
    "src/backend/zuno/core/agents/general_agent.py",
    "src/backend/zuno/core/agents/structured_response_agent.py",
    "src/backend/zuno/core/callbacks/__init__.py",
    "src/backend/zuno/core/callbacks/usage_metadata.py",
    "src/backend/zuno/core/graphs/__init__.py",
    "src/backend/zuno/core/graphs/domain_qa_graph.py",
    "src/backend/zuno/core/graphs/multi_agent_supervisor_graph.py",
    "src/backend/zuno/core/graphs/states.py",
    "src/backend/zuno/core/models/__init__.py",
    "src/backend/zuno/core/models/anthropic.py",
    "src/backend/zuno/core/models/embedding.py",
    "src/backend/zuno/core/models/manager.py",
    "src/backend/zuno/core/models/reason_model.py",
    "src/backend/zuno/core/runtime/__init__.py",
    "src/backend/zuno/core/runtime/agent_runtime.py",
    "src/backend/zuno/main.py",
    "src/backend/zuno/settings.py",
    "src/backend/zuno/config.yaml",
    "src/backend/zuno/prompts/__init__.py",
    "src/backend/zuno/prompts/completion.py",
    "src/backend/zuno/prompts/mcp.py",
    "src/backend/zuno/prompts/rewrite.py",
    "src/backend/zuno/prompts/skill.py",
    "src/backend/zuno/tools/__init__.py",
    "src/backend/zuno/tools/cli_tool/__init__.py",
    "src/backend/zuno/tools/cli_tool/adapter.py",
    "src/backend/zuno/tools/openapi_tool/__init__.py",
    "src/backend/zuno/tools/openapi_tool/adapter.py",
    "src/backend/zuno/tools/send_email/__init__.py",
    "src/backend/zuno/tools/send_email/action.py",
    "src/backend/zuno/tools/send_email/cli.py",
    "src/backend/zuno/tools/image2text/__init__.py",
    "src/backend/zuno/tools/image2text/action.py",
    "src/backend/zuno/tools/text2image/__init__.py",
    "src/backend/zuno/tools/text2image/action.py",
    "src/backend/zuno/utils/__init__.py",
    "src/backend/zuno/utils/JWT.py",
    "src/backend/zuno/utils/constants.py",
    "src/backend/zuno/utils/contexts.py",
    "src/backend/zuno/utils/convert.py",
    "src/backend/zuno/utils/date_utils.py",
    "src/backend/zuno/utils/file_utils.py",
    "src/backend/zuno/utils/hash.py",
    "src/backend/zuno/utils/helpers.py",
    "src/backend/zuno/utils/model_output.py",
    "src/backend/zuno/utils/runtime_observability.py",
    "src/backend/zuno/fixtures/knowledge_reindex/zuno_ascii_kb_001.md",
]


def test_critical_zuno_runtime_chain_does_not_directly_import_agentchat():
    for relative_path in CRITICAL_RUNTIME_FILES:
        content = (REPO_ROOT / relative_path).read_text(encoding="utf-8")
        assert "from agentchat" not in content, relative_path
        assert "import agentchat" not in content, relative_path


def test_workspace_route_now_delegates_runtime_orchestration_to_service_layer():
    relative_path = "services/api/src/zuno/api/v1/workspace.py"
    content = (REPO_ROOT / relative_path).read_text(encoding="utf-8")
    service_content = (
        REPO_ROOT / "services/api/src/zuno/api/services/workspace.py"
    ).read_text(encoding="utf-8")

    assert "from zuno.api.services.workspace import WorkspaceService" in content
    assert "from zuno.api.services.llm import LLMService" not in content
    assert "from zuno.api.services.mcp_server import MCPService" not in content
    assert "from zuno.api.services.agent import AgentService" not in content
    assert "from zuno.services.workspace.simple_agent import MCPConfig, WorkSpaceSimpleAgent" not in content
    assert "from zuno.api.services.llm import LLMService" in service_content
    assert "from zuno.api.services.mcp_server import MCPService" in service_content
    assert "from zuno.api.services.agent import AgentService" in service_content
    assert "from agentchat.api.v1.workspace import *" not in content


def test_migrated_storage_modules_no_longer_live_under_legacy_backend_root():
    for relative_path in LEGACY_FILES_THAT_SHOULD_BE_GONE:
        assert not (REPO_ROOT / relative_path).exists(), relative_path
